[run]
build = "npm run build"

[gptengineer-app]
project_id = "3267aece-5b7b-4c59-8530-567f7f598db9"

[[gptengineer-app.openapi]]
url = "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/color.pizza/1.0.0/openapi.yaml"
